from __future__ import annotations

from pathlib import Path
import subprocess
import sys
import time


REPO_ROOT = Path(__file__).resolve().parent
OUTPUT_DIR = REPO_ROOT / "verification" / "outputs"
REPORT_PATH = REPO_ROOT / "EXPECTED_RESULTS.md"

SCRIPTS = [
    ("Experiment 1(a)", REPO_ROOT / "experiments" / "Ex01_Search" / "bfs.py", "ex01a_bfs.txt"),
    ("Experiment 1(b)", REPO_ROOT / "experiments" / "Ex01_Search" / "dfs.py", "ex01b_dfs.txt"),
    ("Experiment 2(a)", REPO_ROOT / "experiments" / "Ex02_Informed_Search" / "a_star.py", "ex02a_a_star.txt"),
    ("Experiment 2(b)", REPO_ROOT / "experiments" / "Ex02_Informed_Search" / "ao_star.py", "ex02b_ao_star.txt"),
    ("Experiment 3", REPO_ROOT / "experiments" / "Ex03_Naive_Bayes" / "naive_bayes_tennis.py", "ex03_naive_bayes.txt"),
    ("Experiment 4", REPO_ROOT / "experiments" / "Ex04_Bayesian_Networks" / "bayesian_network_heart.py", "ex04_bayesian_network.txt"),
    ("Experiment 5(a)", REPO_ROOT / "experiments" / "Ex05_Regression" / "linear_regression_homeprices.py", "ex05a_linear_regression.txt"),
    ("Experiment 5(b)", REPO_ROOT / "experiments" / "Ex05_Regression" / "logistic_regression_insurance.py", "ex05b_logistic_regression.txt"),
    ("Experiment 6(a)", REPO_ROOT / "experiments" / "Ex06_Trees" / "decision_tree_covid.py", "ex06a_decision_tree.txt"),
    ("Experiment 6(b)", REPO_ROOT / "experiments" / "Ex06_Trees" / "random_forest_covid.py", "ex06b_random_forest.txt"),
    ("Experiment 7", REPO_ROOT / "experiments" / "Ex07_SVM" / "svm_covid.py", "ex07_svm.txt"),
    ("Experiment 8", REPO_ROOT / "experiments" / "Ex08_Ensembling_KMeans" / "kmeans_gmm_iris.py", "ex08_kmeans_gmm.txt"),
    ("Experiment 9", REPO_ROOT / "experiments" / "Ex09_Clustering" / "kmeans_income.py", "ex09_kmeans_income.txt"),
    ("Experiment 10", REPO_ROOT / "experiments" / "Ex10_EM_Bayesian" / "em_coin_toss.py", "ex10_em.txt"),
    ("Experiment 11", REPO_ROOT / "experiments" / "Ex11_Simple_NN" / "simple_neural_network_digits.py", "ex11_simple_nn.txt"),
    ("Experiment 12", REPO_ROOT / "experiments" / "Ex12_DeepLearning_CNN" / "cnn_cellimage.py", "ex12_cnn.txt"),
]


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    rows: list[tuple[str, bool, float, Path]] = []

    for label, script_path, output_name in SCRIPTS:
        start = time.perf_counter()
        completed = subprocess.run(
            [sys.executable, str(script_path)],
            cwd=script_path.parent,
            capture_output=True,
            text=True,
            timeout=600,
        )
        duration = time.perf_counter() - start
        combined_output = completed.stdout
        if completed.returncode != 0 and completed.stderr:
            combined_output = combined_output + "\n[stderr]\n" + completed.stderr

        output_path = OUTPUT_DIR / output_name
        output_path.write_text(combined_output.strip() + "\n", encoding="utf-8")
        rows.append((label, completed.returncode == 0, duration, output_path))

    report_lines = [
        "# Expected Results",
        "",
        "This file was generated by `python verify_all.py`.",
        "",
        "| Experiment | Status | Runtime (s) | Output |",
        "| --- | --- | ---: | --- |",
    ]

    failures = 0
    for label, passed, duration, output_path in rows:
        status = "PASS" if passed else "FAIL"
        if not passed:
            failures += 1
        relative_output = output_path.relative_to(REPO_ROOT).as_posix()
        report_lines.append(f"| {label} | {status} | {duration:.2f} | [{output_path.name}]({relative_output}) |")

    REPORT_PATH.write_text("\n".join(report_lines) + "\n", encoding="utf-8")
    print(f"Wrote report to {REPORT_PATH}")
    print(f"Failures: {failures}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
